parameters:
- name: resource_group
  displayName: Resource Group
  type: string
  default: d3_dev_01
  values:
  - d3_dev_01
  - d3_qa_10

- name: app_service_location
  displayName: App Service Plan Location
  type: string
  default: East US
  values:
  - East US
  - Central US
  - East US 2
  - Central India
  
- name: sku_size
  displayName: App Service Plan SKU & Size
  type: string
  default: FREE
  values:
  - FREE
  - B1
  - B2
  - B3
  - D1
  - F1
  - I1
  - I2
  - I3
  - P1V2
  - P2V2
  - P3V2
  - PC2
  - PC3
  - PC4
  - S1
  - S2
  - S3
  - SHARED
  
- name: is_linux
  displayName: App ServeicePlan Is Linux?
  type: boolean
  default: true
  
  
pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 
  jobs:
  - job: 'CreateUpdate_Azure_WebApp'
    displayName: 'Create or Update Azure WebApp'

    steps:  
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial(dcc87da0-ebd1-425f-a58b-a08f6f1490c9)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az appservice plan create -g ${{parameters.resource_group}} -n MyPlan-linux -l "${{parameters.app_service_location}}" --is-linux --sku ${{parameters.sku_size}}'
        addSpnToEnvironment: true 
      displayName: Azure WebApp for linux   
      condition: and(succeeded(), eq('${{ parameters.is_linux }}', true))
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial(dcc87da0-ebd1-425f-a58b-a08f6f1490c9)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az appservice plan create -g ${{parameters.resource_group}} -n MyPlan-Windows -l "${{parameters.app_service_location}} --sku ${{parameters.sku_size}}'
        addSpnToEnvironment: true 
      displayName: Azure WebApp for windows  
      condition: and(succeeded(), eq('${{ parameters.is_linux }}', false)) 
      

- stage: 
  jobs:
  - job: 'CreateUpdate_Azure_Container_Instance_Group'
    displayName: 'Create or Update Azure Azure conatiner Instance Group'

    steps:  
      
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Free Trial(dcc87da0-ebd1-425f-a58b-a08f6f1490c9)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az container create --resource-group ${{parameters.resource_group}} --file container_instance.yml'
        addSpnToEnvironment: true 
      displayName: Azure WebApp for linux   


